### ISSUE TITLE
Discord invite is invalid

### ISSUE THREAD

**Issue by triphora** [Kotlin-Discord/site#14]
# Description

The [invite](https://discord.gg/gjXqqCS) linked in the READMEs of various Kotlin-Discord repos as well as on the [site](https://kotlindiscord.com) is invalid.

**Comment by gdude2002** [comment]
Hello - this is intentional for the time being. New invites will be set up a bit later.

**Comment by WhiteBlackGoose** [comment]
@gdude2002 hey, what time approximately are you going to make it public? It would be very nice to have a discord community for Kotlin

**Comment by gdude2002** [comment]
At the moment I'm still not in a good situation to open to the public again - it'll happen, but I need to deal with the targeted harassment first

**Comment by WhiteBlackGoose** [comment]
Oh, I see. If you need help moderating the server, let me know.

**Comment by gdude2002** [comment]
I think we're probably OK for now, I've created a new invite.

**Comment by WhiteBlackGoose** [comment]
Doesn't work for me

**Comment by gdude2002** [comment]
Deployment isn't working for some reason, but I've updated the links on the wiki

**Comment by detherminal** [comment]
@gdude2002 I am so sorry for my bad tone man, I thought you arent caring discord server, I didnt know there were some accidents :(
